# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 12:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intakeform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('created_date', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pet',
            name='age',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='primary_breed',
        ),
        migrations.AddField(
            model_name='pet',
            name='active',
            field=models.CharField(default='NULL', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='allergies',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='birth',
            field=models.CharField(default='NULL', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='breed1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='breed2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='build',
            field=models.CharField(default='NULL', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='eats',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='fixed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(default='X', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
