# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intakeform', '0002_auto_20171007_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='user',
        ),
        migrations.AddField(
            model_name='pet',
            name='userprofile_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='intakeform.UserProfile'),
            preserve_default=False,
        ),
    ]
